# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e61d087859822ab648562ed64c1500e2b1c20ebd5c970ec57fc951fd887d2104f7c0b16aa4ef1bf7cae3951763d8ee0fa814359e1a052f789405737d46e4554f

test:
  secret_key_base: 69ac4c59554caa5987927ae81d1c7a5338b07d433a22f6904d4a0c17a41aa7e133fb954c3be006a7f3bbf4261fe55dcff2b7562b512398b350ea0ebfda3db87e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
